### ISSUE TITLE
Add Chinese colors

### ISSUE THREAD

**Issue by Brooooooklyn** [antfu/iroiro#1]
http://www.ylbook.com/cms/web/chuantongsecai/chuantongsecai.htm

**Comment by antfu** [comment]
NP. I have just taken down the npm name `secai`. Do they be offered in JSON format?

**EDIT**: if someone would like to fork this project and make a Chinese version before I really dig into it, let me know and I can transfer the npm name [`secai`](https://www.npmjs.com/package/secai) :P

**Comment by Brooooooklyn** [comment]
> Do they be offered in JSON format

noop...

**Comment by antfu** [comment]
So I guess we would also need to support `secai huang` or `secai 青色` 😄
